# Generated by Django 5.0.2 on 2024-08-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asistencia_fecha_alter_asistencia_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
    ]
